version: '3.9'

services:
  producer:
    build: .
    environment:
      - TIMEOUT=1000
    volumes:
      - "./src/main/resources:/data"
    networks:
      - overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 700M
        reservations:
          cpus: "0.5"
          memory: 500M


networks:
  overlay:
    external: true
    name: story-network
